### ISSUE TITLE
Include an 'add' action to bulk updates

### ISSUE THREAD

**Issue by DarioMavilia** [LuckPerms/LuckPerms#3738] opened 2023-08-18 22:02 UTC
### Description

The add action would allow admins to add new permission nodes to players depending on nodes they already have.

### Proposed Behaviour

Example of the command would be `/lp bulkupdate users add permission.one "permission == permission.two"`. It would allow admins to grant new permissions easily automatically.

**Comment by LeotomasMC** [comment] 2023-08-18 22:05
duplicate of #3151

**Closed** 2023-11-06 22:42 UTC
Labels: type: suggestion
