### ISSUE TITLE
1.20.4 BulkUpdate bug

### ISSUE THREAD

**Issue by Press22300** [LuckPerms/LuckPerms#3846] opened 2024-03-01 00:36 UTC
### Description

When we try to make a bulkupdate on the server, there is an error occured (we are on PurPur 1.20.4, MongoDB storage and LuckPerms 5.4.119). Until 1.20.1, we haven't any issues about that.

![image](https://github.com/LuckPerms/LuckPerms/assets/121343872/a4dc5e5b-c223-4d2b-ad58-73e32a9a30fb)
![image](https://github.com/LuckPerms/LuckPerms/assets/121343872/001ce409-2ba7-4af8-8b47-f3a11e0f0b11)

### Reproduction Steps

Launch a 1.20.4 server, and try to make a BulkUpdate command, to delete a permission from all players

### Expected Behaviour

Delete a permission from all players

### Server Details

git-Purpur-2152 (MC: 1.20.4)

### LuckPerms Version

v5.4.119

**Comment by underscore11code** [comment] 2024-03-01 03:43
There should be more stacktrace, beneath the `caused by`. We'll need that to be able to determine the cause.

**Comment by Press22300** [comment] 2024-03-01 11:11
Thanks for your answer. Here you get all logs of the error (I just edited the backend IP for the MongoDB server)
```
[01:40:16] [luckperms-command-executor/INFO]: [LP] Running bulk update.
[01:40:16] [User Authenticator #0/INFO]: UUID of player Phildelas is 85428757-753c-45c1-b0c9-4422ece5eb32
[01:40:16] [Server thread/INFO]: Disconnecting Phildelas (/92.184.116.47:40110): Le serveur est actuellement fermé !
[01:40:16] [Server thread/INFO]: Phildelas (/92.184.116.47:40110) lost connection: Le serveur est actuellement fermé !
[01:40:17] [luckperms-worker-10/INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:4, serverValue:40956}] to 127.0.0.1:27017
[01:40:17] [luckperms-worker-5/WARN]: java.util.concurrent.CompletionException: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[01:40:17] [luckperms-worker-5/WARN]: Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
[01:40:17] [luckperms-worker-5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.mongodb.MongoStorage.nodeFromDoc(MongoStorage.java:674)
[01:40:17] [luckperms-worker-5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.mongodb.MongoStorage.nodesFromDoc(MongoStorage.java:616)
[01:40:17] [luckperms-worker-5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.mongodb.MongoStorage.processBulkUpdate(MongoStorage.java:278)
[01:40:17] [luckperms-worker-5/WARN]: 	at me.lucko.luckperms.common.storage.implementation.mongodb.MongoStorage.applyBulkUpdate(MongoStorage.java:254)
[01:40:17] [luckperms-worker-5/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$applyBulkUpdate$3(Storage.java:141)
[01:40:17] [luckperms-worker-5/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:98)
[01:40:17] [luckperms-worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[01:40:17] [luckperms-worker-5/WARN]: 	... 6 more
[01:40:17] [luckperms-worker-5/INFO]: [LP] Bulk update failed, check the console for errors.
[01:40:17] [User Authenticator #0/INFO]: UUID of player .RadialMoon28494 is 00000000-0000-0000-0009-01fe5129875e
```

**Comment by Icosider** [comment] 2024-08-24 08:37
I confirm this Issue, I have a similar problem.

**Comment by lucko** [comment] 2024-08-24 08:55
Should be fixed by the above commit :) thanks for reporting

**Closed by lucko** 2024-08-24 08:55 UTC
Labels: type: issue
