### ISSUE TITLE
Doubles Prefix Bug !

### ISSUE THREAD

**Issue by DarrenM999** [LuckPerms/LuckPerms#3355] opened 2022-03-30 07:08 UTC
### Description

Double Prefix Problem !
When I chat on the server, the chat displays something like: [MVP+][MVP+]Rennmaa : <Messages>

### Reproduction Steps

Dont Know

### Expected Behaviour

I only want to use 1 prefix instead of 2 prefixes ! For example :
[MVP+]Rennmaa : <Messages>

### Server Details

Paper MC 1.16.5

### LuckPerms Version

v5.4.9

### Logs and Configs

[config.txt](https://github.com/LuckPerms/LuckPerms/files/8377902/config.txt)

### Extra Details

![image](https://user-images.githubusercontent.com/84304568/160772322-3553a31a-bcc8-4dd5-b3a6-1dd0d3added7.png)

**Comment by ZeromaniacMc** [comment] 2022-03-30 07:40
Hi there!

This is actually not a mistake on LuckPerms' side. If you don't believe me, you can check that with `/lp user <yourname> info`. Your prefix there will show only once. The second prefix is added due to the following reason:

➢ As described inside your essentials config file (chat section), using `{DISPLAYNAME}` and `{PREFIX}` together in your chat format while `'add-prefix-suffix'` is not set to false will result in double prefixes. This is because `{DISPLAYNAME}` equals to `prefix+name`, adding another `{PREFFIX}` in front of it will result in `prefix + prefix + name`.
You have two options to fix this. 
Either:
1.) Find the setting called `'add-prefix-suffix'` in your essentials config and remove the # in front of it and make sure it's set to false 
or
2.) Remove the {PREFIX} placeholder from your chat format since displayname already contains the prefix.

Keep in mind that LuckPerms will never force prefixes into your chat since it's not a chat plugin. 
Hope this helps you.

**Comment by DarrenM999** [comment] 2022-03-30 08:03
![image](https://user-images.githubusercontent.com/84304568/160782135-72c9fdbc-6715-457d-b95a-d951d687e1cc.png)
I write just {DISPLAYNAME} , im not include {PREFIX}

**Comment by ZeromaniacMc** [comment] 2022-03-30 08:04
Yea I saw that afterwards, that's why I asked if you configured meta-stacking in your LuckPerms config. 
Sorry for my slow brain. Could you please show us how you are stacking prefixes in LuckPerms?

**Comment by Turbotailz** [comment] 2022-03-30 08:13
Show output of `/lp user <user> info`

**Comment by DarrenM999** [comment] 2022-03-30 11:53
![image](https://user-images.githubusercontent.com/84304568/160828512-f1ad33c9-1c73-47e6-ab88-bbb173e16d7b.png)

**Comment by DarrenM999** [comment] 2022-03-30 11:56
Thats the output when Im write CMDs "/lp user Rennmaa info
And you can see when I type chat , My name changed to like that , I hope you can help to solve this

**Comment by Turbotailz** [comment] 2022-03-30 23:05
I'm going to close this, as it isn't a LuckPerms issue. You can see that the prefix is configured correctly within LP as confirmed by the user info command.

Your issue is with your chat plugin, maybe show `/plugins` so we can see what plugins you are using that may affect the chat.

Also it would be much easier if you joined our [Discord](https://discord.com/luckperms) to resolve the problem.

**Closed by Turbotailz** 2022-03-30 23:05 UTC
Labels: type: issue

**Comment by DarrenM999** [comment] 2022-03-31 06:59
![image](https://user-images.githubusercontent.com/84304568/160996113-52d0301c-7b29-470d-b00f-88f768ec29c8.png)
Result of /plugins

**Comment by ZeromaniacMc** [comment] 2022-03-31 08:16
Your bedwars plugin has a chat formatting option.
I suggest you disable that and let essentials chat handle it.
