### ISSUE TITLE
Namespaced commands still showing even when disabled

### ISSUE THREAD

**Issue by NonSwag** [LuckPerms/LuckPerms#3847] opened 2024-03-05 15:19 UTC
### Description

As described in the title the namespaced commands for luckperms are still sent even if they are disabled in the spigot.yml config (`commands/send-namespaced`)

![image](https://github.com/LuckPerms/LuckPerms/assets/54660361/3f981ebe-c4f0-4d3a-8bbd-5372c22d60d5)
![image](https://github.com/LuckPerms/LuckPerms/assets/54660361/b28428dc-a21c-4c56-854a-ea2c79d8540f)

### Reproduction Steps

1) Disable the config entry `commands/send-namespaced` in `spigot.yml`
2) Install LuckPerms
3) give yourself all necessary permissions to use LuckPerms

### Expected Behaviour

You should not be able to see the namespaced commands from luckperms

### Server Details

git-Paper-446 (MC: 1.20.4)

### LuckPerms Version

v5.4.116

**Comment by NonSwag** [comment] 2024-05-20 10:19
bump

**Comment by powercasgamer** [comment] 2024-05-20 10:57
Duplicate of https://github.com/lucko/commodore/issues/31

**Closed** 2024-05-20 14:51 UTC
Labels: type: issue
