### ISSUE TITLE
When I delete a user in luckperm web editor, it comes back with UUID no matter how many times I delete it.

### ISSUE THREAD

**Issue by mayu0326** [LuckPerms/LuckPerms#3622] opened 2023-04-08 20:36 UTC
### Description

Using the luckperm web editor, I deleted a user from the user list, reloaded the server or regenerated the editor session, but the user remains in the user list with a UUID.

### Reproduction Steps

1，Launch the Minecraft server on paper,Load luckperms.
2，Execute the "lp editor" command from the server console to generate the URL of the luckperms web editor and open it.
3，Delete one user from the user list through the luckperms web editor and apply the change.
4，Confirm that "[LP] {uuid/minecraftid} was successfully deleted." appears in the server console.
5，Restart the server or run "2，" again to issue a new URL for the luckperms web editor and open it.
6，Check the name field of the user list, and you will see that the user that should have been deleted in "3，" has been changed to a UUID and added again.

### Expected Behaviour

Deleted users will not come back again.

### Server Details

git-Paper-225 (MC: 1.18.2)

### LuckPerms Version

LuckPerms v5.4.41

**Comment by emilyy-dev** [comment] 2023-04-08 21:14
Duplicate of #3595

**Closed by emilyy-dev** 2023-04-08 21:14 UTC
Labels: type: issue
