### ISSUE TITLE
An error occurred when the fabric version was started in offline-mode

### ISSUE THREAD

**Issue by yefeng113** [LuckPerms/LuckPerms#3574] opened 2023-01-29 07:16 UTC
### Description

Error starting server in offline mode

### Reproduction Steps

Set online-mode to FALSE in server.properties
Start Server
Use the client to enter the server
An error occurred

### Expected Behaviour

Being able to Join the server as usual

### Server Details

fabric0.14.12(MC:1.19.3)

### LuckPerms Version

LuckPerms-Fabric-5.4.57

### Logs and Configs

[17:30:16] [luckperms-worker-5/ERROR]:Exception occurred whilst loading data for null - Maplee_leaf
(提示)java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "<parameter1" is null
(提示)at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:?]
(提示)at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.getIfPresent
(提示)(BoundedLocalCache.java:1904) ~[caffeine-2.9.0-remapped.jar:?]
(提示)at me.lucko.luckperms.lib.caffeine.cache.LocalManualCache.getIfPresent
(LocalManualCache.java:57) ~[caffeine-2.9.0-remapped.jar:?]
(提示)at me.lucko.luckperms.common.util.ExpiringSet.contains(ExpiringSet.java:53) ~[%5B权
(提示)限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at me.lucko.luckperms.common.util.ExpiringSet.add(ExpiringSet.java:47) ~[%5B权
(提示)限%5DLuckPerms-Fabric-5.4.57.jar:?]

at me.lucko.luckperms.common.model.manager.user.UserHousekeeper.registerUsage
(提示)(UserHousekeeper.java:58) ~[%5B权限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser
(提示)(AbstractConnectionListener.java:67) ~[%5B权限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.onPreLoginAsync

(FabricConnectionListener.java:98) ~[%5B权限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.lambda$onPreLogin$0
(提示)(FabricConnectionListener.java:80) ~[%5B权限%5DLuckPerms-Fabric-5.4.57.jar:?]
(提示)at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
(提示)at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
(提示)at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]

at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
(提示)at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]

at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
(提示)at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
(提示)[17:30:16] [luckperms-worker-5/信息]:Disconnecting com.mojang.authlib.GameProfile@37709733
(提示)[id=<null,name=Maplee_leaf,配置={},legacy=false] (/218.89.90.148:3308): [LP] 在加载权限数
(提示)据时发生了一个数据库错误. 请稍后再试. 如果你是服务器管理员, 请检查控制台是否有错误.

[17:30:16] [Server thread/信息]:com.mojang.authlib.GameProfile@37709733
(提示)[id=<null,name=Maplee_leaf,配置={},legacy=false] (/218.89.90.148:3308) lost connection:
(提示)[LP] 在加载权限数据时发生了一个数据库错误. 请稍后再试. 如果你是服务器管理员, 请检查控制台是否有错
(提示)误.

**Comment by underscore11code** [comment] 2023-01-29 07:18
Duplicate of #3564

**Closed by underscore11code** 2023-01-29 07:18 UTC
Labels: type: issue, resolution: duplicate
