### ISSUE TITLE
meta weights for any key

### ISSUE THREAD

**Issue by KhaozFrost** [LuckPerms/LuckPerms#3781] opened 2023-11-23 01:28 UTC
### Description

I'd like the ability to have meta weights allowed for any key made.
I like using meta weights for other types of prefixes and such but its not really possible due to how only prefix and suffix weights are acceptable.

### Proposed Behaviour

meta.weight.key

**Comment by emilyy-dev** [comment] 2023-11-23 15:10
Duplicate of #2523

**Closed by emilyy-dev** 2023-11-23 15:10 UTC
Labels: type: suggestion
