### ISSUE TITLE
Neoforge for Minecraft 1.21.3: Invalid Player Data

### ISSUE THREAD

**Issue by RenNagasaki** [LuckPerms/LuckPerms#4001] opened 2024-11-19 08:58 UTC
### Description

Using Luckperms for Neoforge for Minecraft 1.21.3 does not work.

### Reproduction Steps

Install a new Neoforge Server.
Install Luckperms.
Start Server.
Join with a clean Neoforge Client.
Invalid Player Data.

### Expected Behaviour

Install a new Neoforge Server.
Install Luckperms.
Start Server.
Join the Server.
All fine.

### Server Details

neoforge-21.3.28-beta - neoforge-21.3.34-beta --> Tried all Versions

### LuckPerms Version

LuckPerms-NeoForge-5.4.139 - LuckPerms-NeoForge-5.4.146 --> Tried all Versions

### Logs and Configs

Server log: https://gist.github.com/RenNagasaki/26b244b038ca3f691274333bd42ecf0c
Config (Auto created from Mod, not changed): https://gist.github.com/RenNagasaki/1028cd2fed9b1482ecf8f00de49c08b1

**Comment by bloodmc** [comment] 2024-11-24 21:43
@jpenilla Any idea? I was able to reproduce the above error in all versions of LuckPerms running on NeoForge.

**Comment by shield-master** [comment] 2024-11-25 15:07
True
Pls fix it Lucko 😢

**Comment by jpenilla** [comment] 2024-11-25 18:25
Looks like a dupe of #3963

**Comment by lucko** [comment] 2024-12-04 20:46
See comment in #4002, should be fixed by b18717edefabae99a8aa75ee5f49cda2e2ee823c

**Closed by lucko** 2024-12-04 20:46 UTC
Labels: type: issue
