### ISSUE TITLE
Lp user parent set Error

### ISSUE THREAD

**Issue by JJP0808** [LuckPerms/LuckPerms#3585] opened 2023-02-10 07:24 UTC
### Description

Alright, So I am not sure if this is a problem for everyone else but to get started, I am using version 5.4.60 for Luckperms and so I am an Operator/op on my server and, when I use any command that has to do with Luckperms, it says " An unexpected error occurred trying to execute that command" and it has worked before but out of a sudden it gives me that error when using it. Do you know if there is a solution to my problem? Or is it because of version 5.4.60 Luckperms I am running on?

Please message me as soon as it is possible, Thank You for your time.

### Reproduction Steps

Please figure out why this error message is happening.

### Expected Behaviour

![image](https://user-images.githubusercontent.com/116059392/218027879-30ec1347-4e1a-4096-a7c6-76432960526d.png)

It says that message when I use any luckperms command

### Server Details

Spigot (1.19.2)

### LuckPerms Version

v5.4.60

**Comment by underscore11code** [comment] 2023-02-10 07:35
Please follow the issue template, most notably the Logs and Configs section. The root cause of this error will be in your console.

**Comment by JJP0808** [comment] 2023-02-10 07:59
In my console, there isn't any root cause for the error.

**Comment by underscore11code** [comment] 2023-02-10 08:23
Send your full logs please.

**Comment by Anath4n** [comment] 2023-02-16 23:48
I have the same problem, and I don't get any errors in the console or in the logs.

**Closed** 2023-04-30 10:44 UTC
Labels: type: issue
