### ISSUE TITLE
Request to fully Distribute LuckPerms on Modrinth

### ISSUE THREAD

**Issue by Akorian** [LuckPerms/LuckPerms#3928] opened 2024-06-28 20:34 UTC
### Description

I am a user who appreciates the convenience and features of Modrinth, a modern platform for distributing Minecraft plugins and mods. Currently, LuckPerms is only available for download through your own website, which limits the options for automated download and management. 

Centralized download options for users are great because they provide a streamlined and consistent experience, making it easier to find, manage, and update plugins or mods across different platforms or systems.

Modrinth offers an API that simplifies project management and ensures a seamless user experience. By distributing LuckPerms on Modrinth, users like myself who automate plugin downloads would benefit greatly from centralized and standardized distribution channels.

### Proposed Behaviour

I kindly request that LuckPerms consider distributing the plugin on Modrinth alongside your current distribution methods. This would involve:

Uploading LuckPerms to Modrinth under the appropriate categories (e.g., Paper, Bukkit, Sponge, Fabric, Forge, etc.).
Utilizing Modrinth’s API for easy integration and management.
Ensuring automated regular updates via the Modrinth API to maintain consistency and availability.

### Extra Details

Hunting for new versions of plugins or mods on their respective sites is a very tedious and annoying process that also involves the risk of downloading malware mostly for inexperienced users. Looking at windows, I understand that many users are used to hunting for their software, but even windows has embraced centralized software management through winget, and on other platforms like linux, have centralized software downloads since forever.
I believe that Modrinth with their API is the best bet for the Minecraft community at the moment as it makes it easy for everyone to find, distribute and share their passion projects safely.

**Comment by BNTFryingPan** [comment] 2024-06-29 01:51
duplicate of #3545

**Comment by Akorian** [comment] 2024-06-29 12:30
@BNTFryingPan ahh i didnt find that issue. But id say that I provide a little more info in my issue either way ^^

**Comment by Zoriot** [comment] 2024-12-08 19:09
@Akorian i think you Issue is solved?

**Closed** 2024-12-08 19:27 UTC
Labels: type: suggestion
