### ISSUE TITLE
Server lag on command & Freeze

### ISSUE THREAD

**Issue by SladeHazard** [LuckPerms/LuckPerms#3257] opened 2021-12-31 00:15 UTC
### Description

Server lags out for a few seconds on commands when luckperms is connecting to MySQL.

### Reproduction Steps

/lp editor
while connected to my database.

### Expected Behaviour

no lag

### Server Details

1.12.2 Paper

### LuckPerms Version

5.3.89

### Logs and Configs

[19:04:31 INFO]: Archer issued server command: /lp editor
[19:04:41 WARN]: [LuckPerms] Command execution [editor] has not completed. Trace:
  sun.misc.Unsafe.park(Native Method)
  java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
  java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3334)
  java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
  java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.lambda$findMatchingOfflineUsers$9(WebEditorRequest.java:260)
  me.lucko.luckperms.common.webeditor.WebEditorRequest$$Lambda$2479/1144280066.accept(Unknown Source)
  java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
  java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
  java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
  java.util.stream.Sink$ChainedReference.end(Sink.java:258)
  java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:500)
  java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
  java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
  java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
  java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
  java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.findMatchingOfflineUsers(WebEditorRequest.java:259)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.includeMatchingUsers(WebEditorRequest.java:221)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.includeMatchingUsers(WebEditorRequest.java:202)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:90)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:263)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:167)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$2461/943279974.run(Unknown Source)
  java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)

**Comment by OmegaWeaponDev** [comment] 2021-12-31 03:11
Hi @SladeHazard 

If possible, could you please provide the output from `/lp info`

**Comment by lucko** [comment] 2022-02-07 21:32
Duplicate of #3273

will be addressed there

**Closed by lucko** 2022-02-07 21:32 UTC
Labels: type: issue

**Comment by SladeHazard** [comment] 2022-02-07 22:00
oh this issue was just slow mysql connection for me. but it's sad how only a 500ms diff would do this lol
