### ISSUE TITLE
Exception stopping the server [1.19.2 Fabric]

### ISSUE THREAD

**Issue by Skullians** [LuckPerms/LuckPerms#3903] opened 2024-06-01 15:49 UTC
### Description

Heya, upon trying to stop the server, I often get an error saying "Exception stopping the server" that is to do with LuckPerms.
This only happens when a player is still on the server when the server stops.
If no players are online when the stop instruction is issued, everything is fine.

### Reproduction Steps

Download LuckPerms Fabric v5.4.46 on Fabric 1.19.2 version 0.15.11.
(Possibly add the placeholder api hook for fabric too).
Join the server.
Stop the server while still online.

### Expected Behaviour

The server stops with no errors.

### Server Details

Latest Fabric 1.19.2 (0.15.11)

### LuckPerms Version

v5.4.46

### Logs and Configs

https://mclo.gs/Af2Tb1S

### Extra Details

This is on a heavy modpack.

**Comment by Skullians** [comment] 2024-06-01 15:50
Just noticed this is a duplicate of #3857.
That issue has not had much attention.

**Comment by emilyy-dev** [comment] 2024-06-15 23:29
It is indeed a duplicate of that other issue, closing as such in favour of that one.

**Closed by emilyy-dev** 2024-06-15 23:29 UTC
Labels: type: issue
