### ISSUE TITLE
Can't get LuckPerms link on console/rcon

### ISSUE THREAD

**Issue by crimewaffle** [LuckPerms/LuckPerms#3700] opened 2023-07-04 12:11 UTC
### Description

Unable to get LuckPerms session/link when using `lp editor` on console/rcon.

### Reproduction Steps

Run `lp editor` on console/ over rcon

### Expected Behaviour

Should output a link to the editor

### Server Details

paper-1.20.1-60 

### LuckPerms Version

v5.4.98

### Logs and Configs

https://pastebin.com/4kceDD0p

**Comment by emilyy-dev** [comment] 2023-07-04 12:47
Duplicate of #1365

**Closed by emilyy-dev** 2023-07-04 12:47 UTC
Labels: type: issue
