### ISSUE TITLE
Sponge NoClassDefFoundError sometimes

### ISSUE THREAD

**Issue by pietelite** [LuckPerms/LuckPerms#3308] opened 2022-02-09 01:40 UTC
### Description

When I start the server from scratch (no luckperms root folder or config folder), it starts correctly. After usually one or two restarts, I get a `NoClassDefFoundError` for `me/lucko/luckperms/lib/configurate/loader/ConfigurationLoader`. I'm not sure what causes it, but something else that is strange is that the on the first run, the server does not shut down fully. I have to manually close out the console every time I start LuckPerms from scratch.

### Reproduction Steps

- Start up server for the first time
- Shut down (observe console hanging after all "All chunks are saved" messages)
  - Force quit
- Start up server again
- Observe error like [this](https://gist.github.com/pietelite/86f5a0142fe24669f95cf084b89f8134)

### Expected Behaviour

The server should start and shut down normally

### Server Details

spongevanilla-1.16.5-8.0.0-RC1055-universal

### LuckPerms Version

LuckPerms-Sponge-5.3.103

### Logs and Configs

https://gist.github.com/pietelite/86f5a0142fe24669f95cf084b89f8134

**Comment by OmegaWeaponDev** [comment] 2022-02-15 06:41
LuckPerms requires several libraries in order to operate. If you're getting a startup error such as NoClassDefFoundError, ClassNotFoundException or "Unable to load dependency...", stop your server, delete the /plugins/LuckPerms/libs/ directory and start it up again.

**Comment by pietelite** [comment] 2022-02-15 06:57
Are you thinking Bukkit/Spigot when you say the `plugins/LuckPerms/libs` directory? In Sponge, the folders are `mods/` for the jars and another root data directory `luckperms/`. I've already tried deleted all things related to LuckPerms and restarting with no other mods and this same error appears.

I've even created a completely fresh server with `spongevanilla-1.16.5-8.0.0-RC1055-universal` running only `LuckPerms-Sponge-5.3.103` and the issue persists.

**Comment by OmegaWeaponDev** [comment] 2022-02-15 06:58
Try updating to the latest version of Luckperms and see if it still happens

**Comment by pietelite** [comment] 2022-02-15 07:07
After 
1. replacing with `v5.4.2`
2. deleting all luckperms files
3. restarting server
4. adding a new group called "admins"
5. closing server (observing the shut-down process hang and need to be forced shut, as before)
6. restarting with no problems
7. shutting down once more (this time with no error)
8. and then restarting once more

the same errors as before have appeared.

**Comment by lucko** [comment] 2022-02-16 18:55
I've also been able to reproduce this and observed the same thing, happens sometimes and not others.

I think it could be a Sponge classloading issue (perhaps due to parallel loading?).

**Comment by lucko** [comment] 2022-02-17 00:26
Should be resolved in LuckPerms-Sponge-5.4.4, SpongeVanilla 1.16.5-8.0.0-RC1074 and SpongeForge 1.16.5-36.2.5-8.0.0-RC1074

**Closed by lucko** 2022-02-17 00:26 UTC
Labels: type: issue
