### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by SJones-BWGY** [LuckPerms/LuckPerms#3442] opened 2022-07-31 20:32 UTC
### Description

When we put luckperms on our server the command just gives us the 'An unexpected error occurred trying to execute that command' error with an UnsupportedOperationException. We already tried to use the 5.4.30 instead of 5.4.36 and we tried to delete the plugins folder.

### Reproduction Steps

We just installed LuckPerms and tried to run the command and it didn't work.

### Expected Behaviour

The command should work.

### Server Details

git-Paper-94

### LuckPerms Version

v5.4.36

### Logs and Configs

No error message in the console

**Comment by powercasgamer** [comment] 2022-07-31 20:36
duplicate of #3440

**Closed** 2022-08-01 02:03 UTC
Labels: type: issue
