### ISSUE TITLE
pre-login processing for  non-whitelisted player

### ISSUE THREAD

**Issue by SlimeDog** [LuckPerms/LuckPerms#3853] opened 2024-03-13 14:59 UTC
### Description

Occasionally, someone finds my non-public server and attempts to connect. Since they are not whitelisted, the connection fails, but sometimes LuckPerms pre-login processing is performed. On other occasions, such attempts are blocked before LuckPerms sees them. I am not able to ascertain the difference between these cases.

In the former case, an entry is made in LuckPerm's `uuidcache.txt`. I would prefer that did not occur.

### Reproduction Steps

- Login attempt by non-whitelisted player
- Read console/log

### Expected Behaviour

Connection attempt should be ignored.

### Server Details

git-Paper-450 (MC: 1.20.4)

### LuckPerms Version

5.4.120

### Logs and Configs

```
[17:41:06] [User Authenticator #0/INFO]: [LuckPerms] Processing pre-login for 729e4b94-efbe-4619-894e-5bdc2840f663 - KRISHARK110
[17:41:06] [User Authenticator #0/INFO]: UUID of player KRISHARK110 is 729e4b94-efbe-4619-894e-5bdc2840f663
[17:41:06] [Server thread/INFO]: [LuckPerms] Processing login for 729e4b94-efbe-4619-894e-5bdc2840f663 - KRISHARK110
[17:41:06] [Server thread/INFO]: Disconnecting KRISHARK110 (/88.153.136.77:62802): You are not whitelisted on this server!
[17:41:06] [Server thread/INFO]: KRISHARK110 (/88.153.136.77:62802) lost connection: You are not whitelisted on this server!
```

### Extra Details

It is possible that this is a Paper issue, since the content of `whitelist.json` is not being honored. If that is the case, I will open a ticket there.

**Comment by SlimeDog** [comment] 2024-03-13 15:48
Per comment in [https://github.com/PaperMC/Paper/issues/10321](https://github.com/PaperMC/Paper/issues/10321), this should be addressed by plugins.

**Comment by emilyy-dev** [comment] 2024-03-13 15:50
This is not a bug but intended behaviour. Duplicate of #3802

**Closed by emilyy-dev** 2024-03-13 15:50 UTC
Labels: type: issue
