### ISSUE TITLE
Translations not work on spigot-1.20.6 server?

### ISSUE THREAD

**Issue by xiaoACE6716** [LuckPerms/LuckPerms#3884] opened 2024-05-05 16:47 UTC
### Description

As the title says, the translations is not working properly.

### Reproduction Steps

After using /lp translations install to download the file and restart the server, there is no translation.
![image](https://github.com/LuckPerms/LuckPerms/assets/94223505/078d1b49-4ecc-46b3-81d6-9b1455f0c157)
![image](https://github.com/LuckPerms/LuckPerms/assets/94223505/9d65bd2e-3481-45b3-abcc-9708059bcf6a)

### Expected Behaviour

Because I am using Chinese, the return message of the command should also be in Chinese.

### Server Details

spigot-1.20.6

### LuckPerms Version

LuckPerms-Bukkit-5.4.126.jar

### Logs and Configs

https://pastebin.ubuntu.com/p/X33YhrJHrT/

**Comment by BangXi** [comment] 2024-05-11 14:02
duplicate of https://github.com/LuckPerms/LuckPerms/issues/3826

**Comment by lucko** [comment] 2024-06-02 21:18
Can you see if this is fixed by 9805f8b2c41c77afbda83bcd1f14cc1fdb7b6c67 (v5.4.131 or newer - https://luckperms.net/download)

**Closed** 2024-06-03 15:56 UTC
Labels: type: issue
