### ISSUE TITLE
Commands not working 

### ISSUE THREAD

**Issue by SkyDraks** [LuckPerms/LuckPerms#3302] opened 2022-02-04 01:13 UTC
### Description

/luckperms commands do not work. When I do /luckperms editor it says "Unknown or incomplete command, see below for error ...rms editor<--[HERE]" 

### Reproduction Steps

Every time I write a command they don't work. 

### Expected Behaviour

The command is supposed to provide me with a link to access the permissions on the website 

### Server Details

Spigot 1.18.1

### LuckPerms Version

v5.3.89

**Comment by TheMethodicalJosh** [comment] 2022-02-04 01:50
If you are using Minecraft Forge version on your client higher than 39.0.45, this is your issue.

https://github.com/MinecraftForge/MinecraftForge/issues/8438#issuecomment-1029526426

Since LuckPerms is using an older method of registering commands, an update in the Forge custom commands is causing a breakage. Unfortunately the only fix at the moment is to downgrade to 39.0.45 until LuckPerms updates to the newer way of registering commands that mark the commands as executable.

**Comment by lucko** [comment] 2022-02-07 22:28
Duplicate of #3299 - fix will be released shortly

**Closed by lucko** 2022-02-07 22:28 UTC
Labels: type: issue
