### ISSUE TITLE
Folders In Luckperms

### ISSUE THREAD

**Issue by rbcoder117** [LuckPerms/LuckPerms#3817] opened 2024-01-13 05:24 UTC
### Description

I personally think that luckperms can get a bit messy after a while. I think having folders to organize ranks would make the plug-in a lot cleaner!

### Proposed Behaviour

It should be in folders like

Default, 📂 (Rewards)
__________|
  Daily, weekly, etc.

But able to be called like Daily without calling the folder.

**Comment by BNTFryingPan** [comment] 2024-01-13 11:11
duplicate of #3553

**Closed** 2024-01-23 17:52 UTC
Labels: type: suggestion
