### ISSUE TITLE
lag and a error in console

### ISSUE THREAD

**Issue by PANTA9988** [LuckPerms/LuckPerms#3511] opened 2022-10-19 15:21 UTC
### Description

[15:14:08 WARN]: [me.lucko.luckperms.lib.hikari.pool.HikariPool] luckperms-hikari - Thread starvation or clock leap detected (housekeeper delta=50s269ms774µs350ns).
[15:14:08 WARN]: Can't keep up! Is the server overloaded? Running 24724ms or 494 ticks behind
[15:14:08 WARN]: PANTA9988 moved too quickly! -102.41545404826866,0.0,-3.7848312875888723

### Reproduction Steps

onli happends with players in game

### Expected Behaviour

i dont know

### Server Details

git-Paper-215 (MC: 1.19.2)

### LuckPerms Version

v5.4.50

### Logs and Configs

plugins: AdvancedEnchantments, AdvancedGUI*, AnimatedScoreboard, AnimationsCore, ArmorStandTools, AsyncWorldEdit, AuthMe, BanItem, BattlePass, BetterSlimeChunks, BKCommonLib, BuycraftX, ChatColor2, ChatManager, Chunky, Citizens, ClearLag, CommandBlocker, ComplexTurrets, ConditionalEvents, CoreProtect, CrazyEnvoy, CustomizablePlayerModels, DeathChestPro, DecentHolograms, DeluxeMenus, DiscordSRV, DualWield, DungeonParties, Elevator, EpicBackpacks, Essentials, ExcellentCrates, HyperDrive, ImageMaps, Interface4, Iris, ItemEdit, ItemEditor, ItemsAdder, ItemsAdder-WorldEdit, ItemsAdderBlocksInjector, LevelledMobs, LibsDisguises, LightAPI, LoneLibs, LuckPerms, mcMMO, MCPets, MiningBlocks, MMOCore, MMOItems, ModelEngine, My_Worlds, MyCommand, MythicDungeons, MythicLib, MythicMobs, NBTAPI, NexEngine, Oraxen, PlaceholderAPI, PlayerKits, PocketMobs, PortalGun, ProtectionStones, ProtocolLib, PublicCrafters, PV*, QualityArmory, QualityArmoryVehicles2, RandomTeleport, ResourcePackBroadcast, ReviveMe, RHLeafDecay, RPGInventory, SafeNET, ScreenEffects, ServersNPC, Shopkeepers, SimpleTpa*, Spartan, TAB, TradeSystem, UltimateHomes, UltraCustomizer, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidTeleportPlus, VotingPlugin, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, WorldGuardGUI

### Extra Details

the server doesn't crash only dont works for 10 or more seconds and kicks all players

**Comment by LeotomasMC** [comment] 2022-10-19 15:47
something is causing your server to lag. it is not luckperms. from the whopping 3 lines of info you have given i suspect that the issue is chunk loading caused by a player moving too fast. if you actually want to fix this consider at least sending a full log or a timings report. also consider not supporting piracy

**Comment by underscore11code** [comment] 2022-10-19 17:17
The thread starvation or clock leap means this is a fairly major problem, although like @LeotomasMC said, it's not caused by LP.

Either your server is incredibly overloaded (which given the amount of plugins you have, not unlikely), or you have an OS-level issue.

**Closed** 2022-11-26 18:26 UTC
Labels: type: issue
