### ISSUE TITLE
Implement a comment feature

### ISSUE THREAD

**Issue by marioenache** [LuckPerms/LuckPerms#3888] opened 2024-05-12 21:01 UTC
### Description

Hello there,

I've been using luckperms for three years now and I haven't encountered any problems. however, when it comes to a larger network of servers, where luckperms runs in bungee, managing permissions becomes quite complicated. so I came up with a suggestion: a comment function. thus, in the web editor we will have a new column, called comment. users will be able to write a specific message next to the desired permission, which will facilitate the management of hundreds of permissions in more complex game setups.

### Proposed Behaviour

there is not much to explain. it's simply a new column in the editor that adds the possibility of text comments. users will be able to see the message with a single click :)

**Comment by underscore11code** [comment] 2024-05-12 21:04
Duplicate of #3628

**Closed by underscore11code** 2024-05-12 21:04 UTC
Labels: type: suggestion
