### ISSUE TITLE
LuckPerms cannot respond to the request because to do so 

### ISSUE THREAD

**Issue by Gafel98** [LuckPerms/LuckPerms#3959] opened 2024-08-20 14:21 UTC
### Description

So i have a server hosting with Mohist 1.19.2 (i know i lot of people don't like it but is the only oprtion i have to put mod and plugins together in my server host)
I made my self Owner here is the link for the Permissions i made : 

https://luckperms.net/editor/Gkds2kOJGb

plugins in game are all green so they work properly (not really but that's anoth issue i wil ask for help later one)
(plugins i have are : EssentialsXCha , EssentialsX , EssentialsXSpawn , Vault )

When i try to use the comand /gamemode creative or /gmc (thanks to EssentialsX ) it sas the error you can check on the link below:

https://givemelogs.com/6Iq8OVWnznjYlCpdnPgPK

 'vault-unsafe-lookups' is set on true already but still same issue

### Reproduction Steps

have mohist 1.19.2 server install all the plug ins above and try to make my sel owner to use the in game commands

### Expected Behaviour

give me the possibilite to use the owner commands in game chat

### Server Details

Mohist 1.19.2 (mods & plugins)

### LuckPerms Version

v5.4.139

**Comment by BNTFryingPan** [comment] 2024-08-20 14:44
the issue is described in the error there clearly. this is not an issue with luckperms, it is an issue with whatever made the request (which you neglected to include in your paste)

**Comment by Gafel98** [comment] 2024-08-20 15:37
20.08 15:36:28 [Server] INFO Error: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.

**Comment by underscore11code** [comment] 2024-08-20 18:45
The culprit plugin will be in that stacktrace. This is, again, not an issue with LuckPerms, and the error informs you of your options to remedy it.

**Closed by underscore11code** 2024-08-20 18:45 UTC
Labels: type: issue
